# Generated by Django 2.2.16 on 2022-08-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20220812_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='date',
            field=models.DateField(),
        ),
    ]
